[project]
name = "partialg"
version = "0.0.1"
authors = [
  { name="Dennis Lima", email="deaq54989@hbku.edu.qa" },
]
description = "Partial implementations of matrix inversion and diagonalization, and their applications."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
        "numpy>=2.0.2",
        "scipy>=1.16.1",
        "sympy>=1.13.3",
        "matplotlib>=3.9.2",
        "tqdm>=4.67.1"
]

[project.urls]
Homepage = "https://github.com/partialg/partialg"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [".", "partialg"]

[project.license]
file = "LICENSE.txt"
